# Generated by Django 4.1 on 2022-08-11 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='OrderName',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='orders',
            name='Product',
            field=models.CharField(max_length=100),
        ),
    ]
